version: 2.1

workflows:
  workflow:
    jobs:
      - test-with-preinstalled-php:
          name: PHP 8.1
          docker-image: php:8.1-cli-alpine

jobs:
  test-with-preinstalled-php:
    parameters:
      docker-image:
        type: string

    docker:
      # Specify the version you desire here
      - image: <<parameters.docker-image>>

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # prepare the database
      - run: cp .env.ci .env
      - run: php artisan migrate --force
      - run: php artisan key:generate
      - run: php artisan jwt:secret

      # run tests with phpunit or codecept
      - run: composer cs
      - run: composer analyse
      - run: composer test
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output
      - run: composer sec
