on: push
name: CI
jobs:
  pipeline:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Api
      run: |
        cp .env.ci .env
        php artisan key:generate
        php artisan jwt:secret -f

    - name: Validate code style
      run: composer cs

    - name: Analyse code
      run: composer analyse

    - name: Run Testsuite
      run: composer test

    - name: Look for vulnerabilities
      run: composer sec
